// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package name.orionis.cms.extensions.blogroll.model;

import name.orionis.cms.extensions.blogroll.model.BlogrollCategory;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect BlogrollCategory_Roo_Configurable {
    
    declare @type: BlogrollCategory: @Configurable;
    
}
