// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package name.orionis.cms.extensions.dynaimcform.model;

import name.orionis.cms.extensions.dynaimcform.model.DynamicForm;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect DynamicForm_Roo_Configurable {
    
    declare @type: DynamicForm: @Configurable;
    
}
