// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package name.orionis.cms.extensions.content.model;

import name.orionis.cms.extensions.content.model.CategoryIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CategoryIntegrationTest_Roo_Configurable {
    
    declare @type: CategoryIntegrationTest: @Configurable;
    
}
