// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package name.orionis.cms.core.rbac.model;

import name.orionis.cms.core.rbac.model.RbacMenu;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect RbacMenu_Roo_Configurable {
    
    declare @type: RbacMenu: @Configurable;
    
}
