// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package name.orionis.cms.extensions.advertisement.model;

import name.orionis.cms.extensions.advertisement.model.Advertisement;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Advertisement_Roo_Configurable {
    
    declare @type: Advertisement: @Configurable;
    
}
